[diagnostics]
sql_linter = true

[display]
code_editor_font_size = 14
dataframes = "rich"
default_table_max_columns = 50
cell_output = "below"
default_table_page_size = 10
reference_highlighting = false
default_width = "medium"
theme = "light"

[language_servers.ty]

[language_servers.basedpyright]

[language_servers.pylsp]
enable_pylint = false
enable_flake8 = false
enable_ruff = true
enable_mypy = true
enable_pydocstyle = false
enable_pyflakes = false
enabled = false

[ai]
inline_tooltip = false
rules = ""
mode = "manual"

[ai.models]
displayed_models = []
custom_models = []

[save]
format_on_save = false
autosave = "after_delay"
autosave_delay = 1000

[experimental]
chat_modes = true
external_agents = true

[keymap]
preset = "vim"
destructive_delete = true

[keymap.overrides]

[runtime]
std_stream_max_bytes = 1000000
auto_instantiate = false
watcher_on_save = "lazy"
auto_reload = "off"
default_auto_download = []
on_cell_change = "autorun"
reactive_tests = true
default_sql_output = "auto"
output_max_bytes = 8000000

[mcp]
presets = []

[mcp.mcpServers]

[completion]
activate_on_typing = true
copilot = false

[formatting]
line_length = 79

[tool.marimo.runtime]
dotenv = [".env"]

[server]
browser = "default"
follow_symlink = false

[snippets]
include_default_snippets = true
custom_paths = []

[package_management]
manager = "uv"
